config/routes.rb
Depot::Application.routes.draw do

  get "admin" => "admin#index"

  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
  end

  get "store/index"

  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products do
      get :who_bought, :on => :member
    end

    root :to => 'store#index', as: 'store'
  end











end


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Depot</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body data-spy="scroll" data-target=".bs-docs-sidebar" data-twttr-rendered="true">
	<!-- Navbar
    ================================================== -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/"><%= @page_title || t('.title')%></a>
          <div class="nav-collapse collapse">
            <ul class="nav">

              <li class="">
                <%= link_to t('.home'), store_path %>
              </li>
<% if session[:user_id] %>
              <li class="">
                <%= link_to t('.orders'), orders_path %>
              </li>

              <li class="">
                <%= link_to t('.products'), products_path %>
              </li>

              <li class="">
                <%= link_to t('.users'), users_path %>
              </li>

              <li class="">
                <%= link_to t('.logout'), logout_path, method: :delete %>
              </li>
<% else %>
              <li class="">
                <%= link_to t('.login'), login_path, method: :get %>
              </li>
<% end %>
              <li class="">
              <%= form_tag store_path, class: 'locale' do %>
              <%= select_tag 'set_locale',
                  options_for_select(LANGUAGES, I18n.locale.to_s),
                  onchange: 'this.form.submit()' %>
               <%= submit_tag 'submit' %>
               <%= javascript_tag "$('.locale input').hide()" %>
              <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>


<div class="container">
  <div class="row">
      <div class="span3 bs-docs-sidebar">
  <% if @cart %>
    <%= hidden_ul_if(@cart.line_items.empty?, class: "nav nav-list bs-docs-sidenav affix ua-cart") do %>
          <%= render @cart %>
    <% end %>
  <% end %>
      </div>
      <div class="span9">
        <%= yield %>
      </div>

  </div>

</div>

</body>
</html>